services:
  - type: web
    name: minha-aplicacao-java
    env: java
    buildCommand: 'mvn clean install'  # Comando de build para Java
    startCommand: 'java -jar target/minha-aplicacao.jar'  # Comando para rodar a aplicação
    plan: free
    disk: 1GB  # Dependendo do tamanho da aplicação, pode ser necessário ajustar

